server:
  port: 8181

spring:
  application:
    name: Budget
  datasource:
    url: jdbc:postgresql://localhost:5432/budget_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Устанавливаем режим для обновления схемы базы данных
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Указываем диалект PostgreSQL
    show-sql: true  # Включаем вывод SQL запросов в лог
  security:
    user:
      name: user
      password: user
  rabbitmq:
    host: localhost  # Имя хоста для RabbitMQ
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 1

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml

springdoc:
  swagger-ui:
    enabled: true
    url: swagger.yaml
    try-it-out-enabled: false
    syntax-highlight:
      activated: true

grpc:
  client:
    reportService:
      address: static://localhost:9090
      negotiation-type: plaintext