server:
  port: 8181

spring:
  application:
    name: Budget
  datasource:
    url: jdbc:h2:file:./data/budget_app
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: user
      password: user
  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

springdoc:
  swagger-ui:
    enabled: true
    url: swagger.yaml
    try-it-out-enabled: false
    syntax-highlight:
      activated: true

grpc:
  client:
    reportService:
      address: static://localhost:9090
      negotiation-type: plaintext