server:
  port: 50051

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/budget_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Устанавливаем режим для обновления схемы базы данных
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Указываем диалект PostgreSQL
    show-sql: true  # Включаем вывод SQL запросов в лог

  rabbitmq:
    host: localhost  # Имя хоста для RabbitMQ
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 1